Mock server
liftedinit/many-rs pull request #173
Opened 2022-07-27 16:46 UTC by Denommus

## Description

A user can now use a configuration TOML file containing keys and values to assign mock responses to the CLI running in server mode.

This file can either be within the PWD where the server is running from and be called `mockfile.toml`, or it can be passed as the argument `--mockfile`.

## Related Issue

Fixes #164

## Testing

The tests are done via unit testing in the PR itself

## Checklist:

- [X] I have read and followed the CONTRIBUTING guidelines for this project.
- [X] I have added or updated tests and they pass.
- [X] I have added or updated documentation and it is accurate.
- [X] I have noted any breaking changes in this module or downstream modules.

2022-08-01 13:04 UTC, fmorency requested changes
Thanks, Yuri! This is a good first iteration.

I would like to see a real mock file example/test(?), used to interact with real MANY clients!

2022-08-01 13:04 UTC, fmorency commented on src/many-mock/src/lib.rs
> +        // If no file was passed from the command line, read the default path if it exists
Why not put the default value in the clap option?

2022-08-01 15:00 UTC, Denommus commented on src/many-mock/src/lib.rs
> +            "".to_string()
I'm assuming one that doesn't pass a mockfile will not want any mock endpoints, that's why I decided for an empty content.

2022-08-01 15:04 UTC, Denommus commented on src/many-mock/src/lib.rs
> +mod tests {
I agree, but in this case, I'm using tests as feature documentation, not to really enforce anything.

2022-08-01 19:40 UTC, Denommus commented
@fmorency I believe your comments were addressed

2022-08-03 15:13 UTC, fmorency commented
As discussed on Slack,

> I would like to see a real mock file example/test(?), used to interact with real MANY clients!

2022-08-05 13:23 UTC, fmorency requested changes
I like where this is going! Thanks, @Denommus!

I would like you to add a mock test file for the product team which implements every `many-ledger` endpoint. This will allow them to test their Gwen stuff. You could also add a BATs test to test this stuff or any other way you can think of?

I would also like you to add your `rspec` tests to the CI. Right now, those tests are not run, and we don't see any impact on the code coverage.

I'll let @hansl pitch in.

2022-08-08 17:52 UTC, hansl commented on src/many-server/src/server.rs
> +                    let this = self.lock().unwrap();
Let's meet about this. I don't think this is the right way of implementing this. There shouldn't be any changes to `server.rs` IMO.

2022-08-08 20:53 UTC, hansl commented on src/many-server/src/server.rs
> +            .map_err(|many_err: ManyError| ResponseMessage::error(&cose_id.identity, id, many_err))
We should move this into its own PR.

2022-08-11 18:46 UTC, hansl requested changes
First round of comments.

2022-08-11 18:46 UTC, hansl commented on src/many-mock/tests/features/integration.feature
> +Given I request "object"
Just style: can we indent those?

2022-08-11 20:35 UTC, hansl approved these changes

2022-08-11 20:37 UTC, merged