Support fractional seconds
liftedinit/many-rs pull request #209
Opened 2022-10-04 13:41 UTC by Denommus

## Description

Add a f64 variant to Timestamp so that it supports fractional seconds

## Related Issue

Fixes #110 

## Testing

Tested encoding and decoding in a unit test

## Checklist:

- [X] I have read and followed the CONTRIBUTING guidelines for this project.
- [X] I have added or updated tests and they pass.
- [X] I have added or updated documentation and it is accurate.
- [X] I have noted any breaking changes in this module or downstream modules.

2022-10-04 23:16 UTC, hansl approved these changes
LGTM with one note. Can you make sure many-framework still works? Removing `Eq` is a breaking change.

2022-10-04 23:16 UTC, hansl commented on src/many-types/src/timestamp.rs
> +};
```suggestion
use minicbor::{decode, encode, Decode, Decoder, Encode, Encoder};
use minicbor::data::{Tag, Type};
use minicbor::encode::Write;
```

2022-10-05 14:24 UTC, fmorency requested changes
Some minor stuff. Thanks!

2022-10-05 14:24 UTC, fmorency commented on src/many-types/src/timestamp.rs
> +            ManyError::unknown("duration value can not represent system time".to_string())
You can remove `.to_string()`

2022-10-05 14:24 UTC, fmorency commented on src/many-types/src/timestamp.rs
> +                ManyError::unknown("duration value can not represent system time".to_string())
You can remove `.to_string()`

2022-10-05 14:24 UTC, fmorency commented on src/many-types/src/timestamp.rs
> +            Timestamp::Float(a) => *a as u64,
Add a comment as to why this is safe do to.

2022-10-05 14:24 UTC, fmorency commented on src/many-types/src/timestamp.rs
> +}
We should probably handle `checked_add()` as well

2022-10-05 14:24 UTC, fmorency commented on src/many-types/src/timestamp.rs
> +}
While you're modifying this, could you add more test cases?

I want to test edge/limit cases and the `add()` behavior.

2022-10-06 22:27 UTC, Denommus commented
Closed per discussion with @hansl

2022-10-06 22:27 UTC, closed without merging