Refactor Transaction to match spec
liftedinit/many-rs pull request #229
Opened 2022-12-06 19:24 UTC by MavenRain

This PR refactors `Transaction` in the `many-types` module to match specification, as cited in https://github.com/liftedinit/many-rs/issues/207

2022-12-06 20:01 UTC, fmorency requested changes
Thanks oni!

I recommend using `None` instead of `Default` for `request` and `response`.

We're still on the fence about `Default` since a P0 issue was caused by it.

@hansl There's a circular dependency between `many-protocol` and `many-types` if `RequestMessage` and `ResponseMessage` stay in `many-protocol`. Do you have a preference about what to move where?

2022-12-07 17:53 UTC, hansl commented
If you want to eliminate `many-protocol` itself and move everything in `many-types`, that would make sense.

2022-12-07 18:31 UTC, MavenRain commented
> If you want to eliminate `many-protocol` itself and move everything in `many-types`, that would make sense.

Great, I can do that.

2022-12-07 22:48 UTC, MavenRain commented on src/many-types/src/blockchain.rs
> +    pub response: Option<ResponseMessage>,
This is the key change of the PR.

2022-12-07 22:48 UTC, MavenRain commented on src/many-types/src/lib.rs
> +pub fn decode_request_from_cose_sign1(
These were moved from `many-protocol`.

2022-12-08 19:09 UTC, fmorency requested changes
Hey,

`WORKSPACE.bazel` still references `many-protocol`, i.e., the Bazel build is broken.

`README.md` still references `many-protocol`

`src/many-types/BUILD.bazel` still references `many-protocol`

2022-12-08 19:10 UTC, MavenRain commented on README.md
>    many-types --> many-server;
On it

2022-12-08 19:11 UTC, MavenRain commented
> Hey,
> 
> `WORKSPACE.bazel` still references `many-protocol`, i.e., the Bazel build is broken.
> 
> `README.md` still references `many-protocol`
> 
> `src/many-types/BUILD.bazel` still references `many-protocol`

Ugh . . . I had these changes made locally, and thought that I pushed, but forgot to save those files.  I'll push them now.

2022-12-08 19:36 UTC, fmorency reviewed
Thanks!

Can you add the modified Bazel lock files as well, i.e., 

```
$ CARGO_BAZEL_REPIN=workspace bazel sync --only=crate_index
```

and push `Cargo.Bazel.lock` and `cargo-bazel-lock.json`

2022-12-08 19:38 UTC, fmorency commented
Oh, and the Bazel build is still broken

```
➜  many-rs git:(oobi/transaction-impl-to-spec) ✗ bazel build //...:all-targets                            
ERROR: /home/fmorency/dev/many-rs/src/many-identity-dsa/BUILD.bazel:36:13: in rust_library rule //src/many-identity-dsa:many-identity-dsa-for-test: target '//src/many-types:many-types-for-test' is not visible from target '//src/many-identity-dsa:many-identity-dsa-for-test'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: /home/fmorency/dev/many-rs/src/many-identity-dsa/BUILD.bazel:36:13: Analysis of target '//src/many-identity-dsa:many-identity-dsa-for-test' failed
ERROR: Analysis of target '//src/many-identity-hsm:many-identity-hsm-for-test' failed; build aborted: 
INFO: Elapsed time: 5.397s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (434 packages loaded, 10670 targets configured)

```

2022-12-08 19:40 UTC, fmorency commented
One last thing, we are using a fork model. Can you fork the repo and work on a branch on your fork, i.e., NOT a branch upstream?

@hansl it appears we can still push branches upstream. Can you disable that, please?

2022-12-08 20:26 UTC, MavenRain commented
Closing to move to a branch of the fork, instead of having a pull off of the upstream branch

2022-12-08 20:26 UTC, closed without merging