Transaction impl to spec
liftedinit/many-rs pull request #230
Opened 2022-12-08 20:28 UTC by MavenRain

This PR refactors Transaction in the many-types module to match specification, as cited in https://github.com/liftedinit/many-rs/issues/207

2022-12-09 14:58 UTC, fmorency approved these changes
LGTM, thanks!

Wait for the `many-framework` work to be completed before merging this.

2022-12-09 18:35 UTC, fmorency requested changes
We might want to burn the content index (`#[n(1)]`) as per 

https://github.com/many-protocol/specification/blob/main/spec/deprecation.adoc

2022-12-13 17:03 UTC, MavenRain commented on src/many-types/src/blockchain.rs
> +    #[n(2)]
See https://github.com/many-protocol/specification/pull/83 for an explanation of this index shift.

2022-12-13 20:18 UTC, fmorency requested changes
You need to keep the legacy `Transaction` struct somewhere, as you'll need it for the migration.

Check how the `Memo` refactoring was made, especially
- many-types/src/memo.rs
- many-types/src/memo/legacy.rs

2022-12-15 14:13 UTC, fmorency requested changes
You don't need the `merk`-related stuff in `many-error`?

Some minor changes to mimic how the `memo` refactor.

2022-12-15 21:24 UTC, hansl commented on README.md
> +Rust libraries for the [MANY protocol] can be found in (https://github.com/many-types).
Revert this. This should be a link to the specification.

2022-12-17 11:25 UTC, fmorency requested changes
Wait a minute @MavenRain...

This is wrong - you didn't follow the specification.

```
? 1 => bstr .cbor request / bstr .size 0,
? 2 => bstr .cbor response / bstr .size 0,
```

2022-12-19 16:47 UTC, MavenRain commented
Closing in favour of https://github.com/liftedinit/many-rs/pull/234

2022-12-19 16:47 UTC, closed without merging