Add transfer endpoint to kvstore
liftedinit/many-rs pull request #236
Opened 2022-12-20 22:05 UTC by hansl

2022-12-21 14:55 UTC, fmorency reviewed
The code LGTM, but I'm wondering why you need two address parameters. 

See https://github.com/many-protocol/specification/pull/86#discussion_r1053716809

2022-12-22 19:32 UTC, fmorency requested changes
I can't comment directly in the code so here it is.

- `owner` in `KvStorePut` event should not be an `Option`
- `owner` in `KvStoreDisable` event should be removed. 
- `reason` in `KvStoreDisable` should have id `2` and should not be an `Option`

You should add the new `canKvStoreTransfer` role in `_9_account.rs` and `_9_account/features/kvstore.rs`

2022-12-22 19:32 UTC, fmorency commented on src/many-modules/src/_4_events.rs
> +        2     | owner:                  Option<Address>                        [ id_non_null ],
`owner` should not be an `Option`

2022-12-22 20:23 UTC, hansl commented on src/many-modules/src/_4_events.rs
> +        2     | owner:                  Option<Address>                        [ id_non_null ],
Did you review the right file/commit?

2022-12-22 20:53 UTC, fmorency approved these changes
LGTM assuming CI passes

2023-01-10 18:25 UTC, merged