Add support for inner listing of addresses in event log
liftedinit/many-rs pull request #243
Opened 2023-01-12 05:55 UTC by hansl

This requires that sub-types of multisig (anything types that are used in fields with an inner tag) implement a trait, so I added a tag for Multisig arguments that defaults to empty set instead if the trait is not implemented. Some types would never implement it anyway.

I re-enabled the test that was disabled, and added a new test for a level 2 recursion. This should be enough to tell us it covers ALL recursive event logs.

Test coverage could be improved but if it builds it works.

2023-01-16 15:09 UTC, fmorency requested changes
Thanks!

nit: better comment the macros.

2023-01-16 15:09 UTC, fmorency commented on src/many-modules/src/_4_events.rs
>  #[cfg(test)]
Can you add a test covering all event types with addresses?

2023-01-16 15:09 UTC, fmorency commented on src/many-modules/src/_4_events.rs
>              }
Is this even used anymore?

2023-01-24 01:00 UTC, hansl commented on src/many-modules/src/_4_events.rs
>              }
Nope, removed.

2023-01-24 13:42 UTC, fmorency approved these changes

2023-01-24 13:42 UTC, merged